version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OmegaDB
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080